### ISSUE TITLE
Only last defined Image Target recognized when multiple Image Targets defined?

### ISSUE THREAD

**Issue by adrianbautista** [GoogleChromeLabs/perception-toolkit#126] opened 2019-06-12 12:04 UTC
Hey 👋 ,

I was following along the simple demo example, but had some issues getting multiple target images to work with the kit. Here's an example commit with an additional image target defined in the simple demo with some details on what I was encountering in the commit description:

https://github.com/adrianbautista/perception-toolkit/commit/ad7e4c37f61a9ffb963b316ad9cc4bf761b5696c

> ...When first starting the simple demo, kit only seems to store only instances of the last image target (*rocks*). But if I stop the kit and start it again, it will say two image targets stored
(*lighthouse*, *rocks*). However when showing the lighthouse image to the camera the kit recognizes *rocks* before *lighthouse* thereby rendering the *rocks* card instead.

And some console screenshots:

<img width="531" alt="first-start" src="https://user-images.githubusercontent.com/2622040/59349829-c7269d80-8d44-11e9-95fe-d03fd014ce40.png">

*simple demo first load*

---

<img width="495" alt="second-start" src="https://user-images.githubusercontent.com/2622040/59349831-c7bf3400-8d44-11e9-8140-139b880e3a9a.png">

*simple demo reloaded*

---

<img width="421" alt="redundant-detection" src="https://user-images.githubusercontent.com/2622040/59349832-c7bf3400-8d44-11e9-8508-892e44ad42ad.png">

*simple demo reloaded, attempt at recognizing the first Image Target defined in artifactSources*

So wanted to double check if I'm misunderstanding how planar tracking is used for the image targets. I'm still debugging this, but let me know if any additional information/context could be helpful!

**Comment by mmocny** [comment] 2019-06-12 13:02
Hello!  Thanks for digging in to the toolkit 👍 

First question: how did you create the rocks.pb file?  Did you perhaps just copy and rename the lighthouse.pb file?

Unfortunately, the image detector right now cannot use the jpg media directly, and has to be pre-processed first.  I do not believe the tool we use to do this has been published to this repo just yet.  (ping @paullewis for update on that)

However, we may be able to generate the pb file for you in the interim.


If thats not the problem, then I can take a look at any issues with multiple image targets.

**Comment by paullewis** [comment] 2019-06-12 13:24
Hey! Seconded, thanks for checking things out. The generator tool is here, in case you hadn't found it already: https://github.com/GoogleChromeLabs/perception-toolkit/tree/master/target-generation

I'm super curious about issue reproduction. The only time I've seen this is when the targets are really similar and the detector detects both (and yes we currently pop the most recent by default.

**Comment by mmocny** [comment] 2019-06-12 14:21
...Looking at the patch referenced, the binary PB file is indeed not the same as the lighthouse example.

I'll wait for Adrian to confirm they followed the target-generation steps, but likely we'll want to dig into this one.

**Comment by adrianbautista** [comment] 2019-06-13 00:35
@mmocny @paullewis I followed the target-generation steps and preprocessed the rocks JPG using:

```shell
$ node target-generation/generator.js --files=./demo/simple/pages/rocks.jpg --dest=./demo/simple/pages
```

I was displaying the target images on another phone's screen, so maybe I'll try the images on a different surface (e.g. print the target images on paper)?

**Comment by paullewis** [comment] 2019-06-13 08:59
I'll take a look at this now, see if I can repro :)

**Comment by adrianbautista** [comment] 2019-06-13 10:00
Some quick updates from my end, I had better luck getting the simple demo to respond to two different images if I only specified the image detector during configuration:

```js
window.PerceptionToolkit.config = {
  ...
  detectors: { 'image': 1 }
};
```

**Comment by adrianbautista** [comment] 2019-06-13 10:11
So with the rocks and lighthouse images and by explicitly setting the image detector only, I'm able to get a version of the simple demo working on both an iPhone and Android phone. Let me know if either of you're able to recreate my original issue, otherwise thanks for sharing this library and looking forward to hacking on it more 🙌.

**Comment by paullewis** [comment] 2019-06-13 10:47
Alright, think I figured this out (PR #127).

Essentially there's a race condition with adding targets such that adding one target can overlap with another thanks to the image detector worker communication. I've ensured that whatever comes back from the worker when we call `add` is treated as the source of truth (not what was passed into the main thread side function), so that if they come back out of order we still store the correct stuff.

When the PR lands, @adrianbautista if you'd be willing to try again (and I'm pleased that it's working for you atm, though I fear that might be because of chance!) that'd be awesome.

**Comment by paullewis** [comment] 2019-06-13 10:48
@mmocny Also added #128 as a TODO for me so we don't regress here.

**Comment by adrianbautista** [comment] 2019-06-14 07:27
@paullewis thanks for the quick response and commit, I pulled down the latest version of master and multiple image targets have been working more consistently. 🙌

I did occasionally encounter a situation in which the image targets were logged as loaded, but then the toolkit wasn't detecting any images and `Detector.detect()` wasn't logging "Time Taken: ...". There were 2 cases in which I could produce this on an iPhone:

![unidentified-target-stored](https://user-images.githubusercontent.com/2622040/59491049-5603f900-8eb0-11e9-9f74-dfcc996b95f7.png)

*an unidentified target was logged (could this be the attemptData?)*

---

![reset](https://user-images.githubusercontent.com/2622040/59490523-1b4d9100-8eaf-11e9-9237-e1e98b3d2f57.png)

*when resetting the toolkit in browser*

---

These seem to be edge-cases though as it doesn't happen each time — could it be another race condition or old cache issue in which the detector is unaware of the loaded image targets?

**Comment by paullewis** [comment] 2019-06-14 11:45
Okay, I have a new patch for this where all messages are explicitly tagged with an ID. That simplifies matters by providing a single worker callback in which we locate the correct callback based on the ID.

**Comment by paullewis** [comment] 2019-06-18 10:43
Okay #131 is merged. @adrianbautista do you have time to test for me?

**Comment by adrianbautista** [comment] 2019-06-20 11:38
Hey @paullewis, pulled down the latest version of master with the worker message IDs, this is what I can see now when debugging:

<img width="618" alt="Screen Shot 2019-06-20 at 6 24 43 PM" src="https://user-images.githubusercontent.com/2622040/59846222-7688f300-9389-11e9-9d54-505a5db93044.png">

I was having some issues with `beginDetection()` not resolving completely, which left the "Initializing detectors" message and loader still visible (happened when detectors was set to image or barcode only), so was trying to track down why `this.startupDetections` wasn't able to finish all of its promises. 

When I had `detectors: { 'barcode': true }` configured, `await Promise.all(this.startupDetections)` in `beginDetection()` wouldn't finish, but I the app was still able to recognize barcode artifacts. Still debugging, but let me know if you have any other ideas.

**Comment by paullewis** [comment] 2019-06-20 12:29
Hmm, I'll take a look. We are refactoring this code a bunch at the moment, and our test coverage needs improvement.

**Comment by paullewis** [comment] 2019-06-20 12:55
@adrianbautista I'm struggling to repro on my end. Which device + browser are you testing on?

**Comment by adrianbautista** [comment] 2019-06-21 03:53
@paullewis was testing it on an Android phone using Chrome with the library rebuilt from the latest master commit. But I'll spend some time today trying the bare minimum simple demo to see if I still encounter the unidentified ID worker message, it could be one of my image targets or the custom `PerceivedResults` event I have that is causing the issue.

**Comment by adrianbautista** [comment] 2019-06-21 08:36
@paullewis restarted my demo from a fork of the perception-toolkit repo and have been unable to reproduce the unidentified worker messages I was encountering before too. So it was most likely some of my own code code or off-build I had in my other demo that was causing issues. Multiple image targets are working consistently for me in the fork and I'm able to track the worker messages in the console.

Thanks again for being responsive and engaging with the original issue, I appreciate the help.

**Comment by paullewis** [comment] 2019-06-21 11:58
Well that's jolly good news. Happy if I close the issue?

**Comment by adrianbautista** [comment] 2019-06-24 03:11
Yeah should be good to close the issue

**Comment by paullewis** [comment] 2019-06-24 13:01
👍

**Closed by paullewis** 2019-06-24 13:01 UTC
